# Creates a Pre-Release Release Candidate Github Tag 
# and Release when PR is merged/closed to develop
# Use PR label
  # norelease - when you do not want to release rc candidate but want to merge

name: Release Candidate

on:
  pull_request:
    types: [closed]
    branches: [develop]

jobs:
  check: 
    runs-on: ubuntu-latest
    steps:
      - name: Exit gracefully if not a release
        id: releaseExitStep
        run: |
          echo "::set-output name=should_release::true"
          if [[ ${{ contains(github.event.pull_request.labels.*.name, 'norelease') }} = "true" ]]; then
            echo "::set-output name=should_release::false"
          fi
    outputs:
      status: ${{steps.releaseExitStep.outputs.should_release}}


  release:
    runs-on: ubuntu-latest
    needs: check
    if: github.event.pull_request.merged == true && needs.check.outputs.status == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm ci

      - name: Set git user
        run: git config user.name ${{ github.actor }} && git config user.email ${{ github.actor }}@users.noreply.github.com
      
      - name: Release a Release Candidate version
        run: npm run release:rc
        id: releaseStep
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
